config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'toppages/index'
  #root to: 'runs#index' 下に変えた
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :runs
  
=begin
  # CRUD
  get  'runs/:id', to: 'runs#show'
  post 'runs', to: 'runs#create'
  put 'runs/:id', to: 'runs#update'
  delete 'runs/:id', to: 'runs#destroy'
  
  # index: showの補助ページ
  get 'runs', to: 'runs#index'
  
  # new: 新規作成ようのフォームページ
  get 'runs/new', to: 'runs#new'
  
  # edit: 更新ようのフォームページ
  get 'runs/:id/edit', to: 'runs#edit'
=end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/run.rb
class Run < ApplicationRecord
    validates :date, presence: true, length: { maximum: 255 }
    validates :name, presence: true, length: { maximum: 255 }
    validates :distance, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 50 }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :update]
  
  def index
      @runs = Run.order(date: :desc).page(params[:page]).per(10)
  end

  def show
      @run = Run.find(params[:id])
  end

  def new
    @run = Run.new
  end

  def create
    @run = Run.new(run_params)

    if @run.save
      flash[:success] = 'ランニング記録が正常に投稿されました'
      redirect_to @run
    else
      flash.now[:danger] = 'ランニング記録ssが投稿されませんでした'
      render :new
    end
  end

  def edit
    @run = Run.find(params[:id])
  end

  def update
    @run = Run.find(params[:id])

    if @run.update(run_params)
      flash[:success] = 'ランニング記録は正常に更新されました'
      redirect_to @run
    else
      flash.now[:danger] = 'ランニング記録は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @run = Run.find(params[:id])
    @run.destroy

    flash[:success] = 'ランニング記録は正常に削除されました'
    redirect_to runs_url
  end
    
end

  private

  # Strong Parameter
  def run_params
    params.require(:run).permit(:date, :name, :distance)
  end
  
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    name = params[:session][:name]
    password = params[:session][:password]
    if login(name, password)
      flash[:success] = 'ログインに成功しました。'
      #redirect_to @user
      redirect_to runs_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end        
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url    
  end

  private

  def login(name, password)
    @user = User.find_by(name: name)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
  end

  def show
  end

  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">TMC Running Record</a>
    <!-- 横幅が狭い時に出るハンバーガーボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- メニュー項目 -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
            <!-- <li class="nav-item"><%= link_to  '新しいランニングの記録', new_run_path, class: 'nav-link' %></li>  -->
            <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
            <!-- <li class="nav-item"><a href="#" class="nav-link">Signup</a></li> -->
            <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RunRecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/runs/_form.html.erb
<div class="row">
  <div class="col-6">

    <%= form_with(model: run, local: true) do |f| %>
      <% if run.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul>
            <% message.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
     
      <div class="form-group">
        <%= f.label :date, '日付' %>
        <%= f.date_select :date, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :distance, '走った距離(km)' %>
        <%= f.number_field :distance, class: 'form-control' %>
      </div>
    
      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
    
  </div>
</div>

app/views/runs/edit.html.erb
<h1><%= @run.date %> : <%= @run.name %> のランニング記録の編集</h1>

<%= render 'form', run: @run %>

app/views/runs/index.html.erb
<h1>ランニング記録一覧</h1>

<% if @runs.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>日付</th>
        <th>名前</th>
        <th>走った距離(km)</th>
      </tr>
    </thead>
    <tbody>
      <% @runs.each do |run| %>
        <tr>
          <td><%= run.date %></td>
          <td><%= link_to run.name, run %></td>
          <td><%= run.distance %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @runs %>
  </div>
<% end %>

<%= link_to '新しいランニングの記録', new_run_path, class: "btn btn-primary" %>

app/views/runs/new.html.erb
<h1>新規作成</h1>

<%= render 'form', run: @run %>

app/views/runs/show.html.erb
<h1><%= @run.date %> : <%= @run.name %> のランニング記録の詳細</h1>

<table class="table table-bordered">
  <tr>
    <th>日付</th>
    <td><%= @run.date %></td>
  </tr>
  <tr>
    <th>名前</th>
    <td><%= @run.name %></td>
  </tr>
  <tr>
    <th>走った距離(km)</th>
    <td><%= @run.distance %></td>
  </tr>
</table>

<%= link_to 'このランニング記録を編集する', edit_run_path(@run), class: 'btn btn-light' %>
<%= link_to 'このランニング記録を削除する', @run, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
<%= link_to '一覧に戻る', runs_path, class: 'btn btn-secondary' %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>

<% else %>
<div class="center jumbotron">
  <div class="text-center">
    <h1>Welcome to TMC Runnnig Record</h1>
  </div>
</div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>